apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
spec:
 replicas:1
template:
  metadata:
     labels:
        app: myapp
 spec:
  containers:
  - name: myapp-pod
    image: us.icr.io/cloud-demo
   ports:
   -containerPort: 9090 

